# Generated by Django 3.1.2 on 2020-10-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201014_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='points',
            new_name='score',
        ),
    ]
