# Generated by Django 3.1.2 on 2020-10-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Question-ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('body', models.TextField(max_length=500, verbose_name='Body')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Date & Time')),
            ],
        ),
    ]
