# Generated by Django 3.1.2 on 2020-10-14 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Answer-ID')),
                ('body', models.TextField(max_length=500, verbose_name='Body')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Date & Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
    ]
