# Generated by Django 3.1.2 on 2020-10-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20201014_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AddField(
            model_name='answer',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='Vote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votes'),
            preserve_default=False,
        ),
    ]
