# Generated by Django 3.1.2 on 2020-10-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20201014_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='vote',
            new_name='votes',
        ),
    ]
